version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27017:27017"    # Forward host port 27017 to container port 27017 (MongoDB default port)
