name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB containers
        run: docker-compose -f db/docker-compose.yml up -d

      - name: Wait for MongoDB to initialize
        run: docker-compose -f db/docker-compose.yml exec mongodb_test bash -c "while ! nc -z localhost 27018; do sleep 1; done"

      - name: Run database setup script
        run: npm run db-setup   # Replace with the actual script name if different

      - name: Run tests
        run: npm run test

      - name: Stop MongoDB containers
        run: docker-compose -f db/docker-compose.yml down
